#!/bin/bash

# 使用 until 循环,直到 who 命令的输出中包含参数 $1(即指定的用户名)
until who | grep "$1" > /dev/null
do
  # 每隔 60 秒检查一次
  sleep 60
done

# 当检测到指定用户登录时,响铃并宣布用户登录
echo -e '\a'
echo "***** $1 has just logged in *****"

# 退出脚本
exit 0
