#!/bin/sh

# 询问用户是否是早上
echo -n "现在是早晨吗?请回答是或否:"
# 读取用户的输入
read timeofday

# 判断用户输入是否为"是",表示现在是早晨
if [ "$timeofday" = "是" ]
then
  # 如果是早晨,打印问候语
  echo "早上好"
# 判断用户输入是否为"否",表示现在不是早晨(假设是下午)
elif [ "$timeofday" = "否" ]; then
  # 如果不是早晨,打印问候语
  echo "下午好"
else
  # 如果用户输入既不是"是"也不是"否",提示用户输入不正确,并退出程序
  echo "对不起,$timeofday 无法识别.请输入是或否"
  exit 1
fi

# 程序正常结束
exit 0
