#!/bin/sh
# 上面的行是脚本的 shebang,它告诉操作系统使用哪个解释器来执行此脚本.在这里,我们使用了 /bin/sh.

echo "现在是早晨吗?请回答是(yes)或否(no)"
# 这行代码输出提示信息,询问用户现在是早晨还是其他时间.

read timeofday
# 这行代码从标准输入读取用户的回答,并将其存储在变量 timeofday 中.

if [ $timeofday = "yes" ] || [ $timeofday = "是" ];
# 如果用户回答"是",则执行以下代码块.
then
  echo "早上好"
  # 输出早上好.
elif [ $timeofday = "no" ] || [ $timeofday = "否" ]; then
  # 如果用户回答"否",则执行以下代码块.
  echo "下午好"
  # 输出下午好.
else
  # 如果用户既没有回答"是"也没有回答"否",则执行以下代码块.
  echo "对不起,$timeofday 无法识别.请输入是或否"
  # 输出错误信息.
  exit 1
  # 以非零状态退出脚本,表示发生了错误.
fi
# if-elif-else 结构结束.

exit 0
# 以零状态退出脚本,表示脚本正常执行完毕.
