#!/bin/sh

# 提示用户输入密码
echo "Enter password"
# 读取用户尝试输入的密码
read trythis

# 当用户输入的密码不是"secret"时,循环执行以下步骤
while [ "$trythis" != "secret" ]; do
  # 通知用户密码错误,需要重新尝试
  echo "Sorry, try again"
  # 再次读取用户尝试输入的密码
  read trythis
done
# 如果用户输入正确的密码,退出脚本并返回状态码0
exit 0

